id: PADB4F6FB
initial_creation_type: input
source_metadata:
  title: The Great Religious History by Sa skya paṇḍi ta (1182–1251)
  author: ས་སྐྱ་པཎྜི་ཏ་ཀུན་དགའ་རྒྱལ་མཚན།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2020-01-18);
    no thematic TEI markup'
  source: https://sakyaresearch.org
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།; This text was published by the Paltsek Research
    Institute. (src)
  - Text input:དཔལ་བརྩེགས་བོད་ཡིག་དཔེ་རྙིང་ཞིབ་འཇུག་ཁང་། (Lhasa) (pts)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/4640
  bases:
    a81b:
      title: The Great Religious History by Sa skya paṇḍi ta (1182–1251)
      order: 1
      base_file: a81b.txt
created_at: '2022-04-15T19:08:28.588460'
last_modified_at: '2022-04-15T19:08:28.588468'
quality: null
